# Generated by Django 5.2 on 2025-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_savedchart_columns_json_savedchart_preview_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedchart',
            name='settings_json',
            field=models.JSONField(default=dict),
        ),
    ]
