# Generated by Django 6.0.3 on 2026-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_savedchart_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ui_theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=8),
        ),
    ]
